In [1]:
import pandas as pd
counts = pd.Series([632, 1638, 456, 112])
print(counts)

0     632
1    1638
2     456
3     112
dtype: int64


In [2]:
counts.values

array([ 632, 1638,  456,  112], dtype=int64)

In [3]:
counts.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
bacteria = pd.Series([632, 1638, 569, 115], index=['Firmicutes', 'Proteobacteria', 'Actinobacteria', 'Bacteroidetes'])
print(bacteria)

Firmicutes         632
Proteobacteria    1638
Actinobacteria     569
Bacteroidetes      115
dtype: int64


In [5]:
bacteria['Actinobacteria']

569

In [6]:
bacteria[bacteria.index.str.endswith('bacteria')]

Proteobacteria    1638
Actinobacteria     569
dtype: int64

In [7]:
'Bacteroidetes' in bacteria

True

In [8]:
bacteria[0]

632

In [9]:
bacteria.name = 'counts'
bacteria.index.name = 'phylum'
print(bacteria)

phylum
Firmicutes         632
Proteobacteria    1638
Actinobacteria     569
Bacteroidetes      115
Name: counts, dtype: int64


In [10]:
import numpy as np
np.log(bacteria)

phylum
Firmicutes        6.448889
Proteobacteria    7.401231
Actinobacteria    6.343880
Bacteroidetes     4.744932
Name: counts, dtype: float64

In [11]:
bacteria[bacteria > 1000]

phylum
Proteobacteria    1638
Name: counts, dtype: int64

In [13]:
bacteria_dict = {'Firmicutes': 632, 'Proteobacteria': 1632, 'Actinobacteria': 569, 'Bacteroidetes': 115}

In [14]:
bact = pd.Series(bacteria_dict)
print(bact)

Firmicutes         632
Proteobacteria    1632
Actinobacteria     569
Bacteroidetes      115
dtype: int64


In [15]:
bacteria2 = pd.Series(bacteria_dict, index=['Cyanobacteria', 'Firmicutes', 'Proteobacteria', 'Actinobacteria'])
print(bacteria2)

Cyanobacteria        NaN
Firmicutes         632.0
Proteobacteria    1632.0
Actinobacteria     569.0
dtype: float64


In [16]:
bacteria2.isnull()

Cyanobacteria      True
Firmicutes        False
Proteobacteria    False
Actinobacteria    False
dtype: bool

In [17]:
bacteria + bacteria2

Actinobacteria    1138.0
Bacteroidetes        NaN
Cyanobacteria        NaN
Firmicutes        1264.0
Proteobacteria    3270.0
dtype: float64

In [18]:
bacteria_data = pd.DataFrame({'value': [632, 1638, 569, 115, 433, 1130, 754, 555],
                             'patient': [1, 1, 1, 1, 2, 2, 2, 2],
                             'phylum': ['Firmicutes', 'Proteobacteria', 'Actinobacteria', 'Bacteroidetes', 'Firmicutes', 'Proteobacteria', 'Actinobacteria', 'Bacteroidetes']})
bacteria_data

value  patient          phylum
0    632        1      Firmicutes
1   1638        1  Proteobacteria
2    569        1  Actinobacteria
3    115        1   Bacteroidetes
4    433        2      Firmicutes
5   1130        2  Proteobacteria
6    754        2  Actinobacteria
7    555        2   Bacteroidetes

In [19]:
bacteria_data[['phylum', 'value', 'patient']]

phylum  value  patient
0      Firmicutes    632        1
1  Proteobacteria   1638        1
2  Actinobacteria    569        1
3   Bacteroidetes    115        1
4      Firmicutes    433        2
5  Proteobacteria   1130        2
6  Actinobacteria    754        2
7   Bacteroidetes    555        2

In [20]:
bacteria_data.columns

Index(['value', 'patient', 'phylum'], dtype='object')

In [21]:
bacteria_data['value']

0     632
1    1638
2     569
3     115
4     433
5    1130
6     754
7     555
Name: value, dtype: int64

In [22]:
type(bacteria_data['value'])

pandas.core.series.Series

In [23]:
bacteria_data[['value']]

value
0    632
1   1638
2    569
3    115
4    433
5   1130
6    754
7    555

In [24]:
bacteria_data.head()

value  patient          phylum
0    632        1      Firmicutes
1   1638        1  Proteobacteria
2    569        1  Actinobacteria
3    115        1   Bacteroidetes
4    433        2      Firmicutes

In [25]:
bacteria_data.tail(3)

value  patient          phylum
5   1130        2  Proteobacteria
6    754        2  Actinobacteria
7    555        2   Bacteroidetes

In [26]:
bacteria_data.shape

(8, 3)

In [35]:
bacteria_data = pd.DataFrame([{'patient': 1, 'phylum': 'Firmicutes', 'value': 632},
{'patient': 1, 'phylum': 'Proteobacteria', 'value': 1638},
{'patient': 1, 'phylum': 'Actinobacteria', 'value': 569},
{'patient': 1, 'phylum': 'Bacteroidetes', 'value': 115},
{'patient': 2, 'phylum': 'Firmicutes', 'value': 6433},
{'patient': 2, 'phylum': 'Proteobacteria', 'value': 1130},
{'patient': 2, 'phylum': 'Actinobacteria', 'value': 754},
{'patient': 2, 'phylum': 'Bacteroidetes', 'value': 555}])
bacteria_data



patient          phylum  value
0        1      Firmicutes    632
1        1  Proteobacteria   1638
2        1  Actinobacteria    569
3        1   Bacteroidetes    115
4        2      Firmicutes   6433
5        2  Proteobacteria   1130
6        2  Actinobacteria    754
7        2   Bacteroidetes    555

In [36]:
vals = bacteria_data.value
vals

0     632
1    1638
2     569
3     115
4    6433
5    1130
6     754
7     555
Name: value, dtype: int64

In [37]:
vals[5] = 0

C:\Users\JON\AppData\Local\Temp/ipykernel_10164/2794464284.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  vals[5] = 0


In [38]:
bacteria_data

patient          phylum  value
0        1      Firmicutes    632
1        1  Proteobacteria   1638
2        1  Actinobacteria    569
3        1   Bacteroidetes    115
4        2      Firmicutes   6433
5        2  Proteobacteria      0
6        2  Actinobacteria    754
7        2   Bacteroidetes    555

In [39]:
bacteria_data.value[5] = 1130

C:\Users\JON\AppData\Local\Temp/ipykernel_10164/2034502601.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bacteria_data.value[5] = 1130


In [40]:
bacteria_data

patient          phylum  value
0        1      Firmicutes    632
1        1  Proteobacteria   1638
2        1  Actinobacteria    569
3        1   Bacteroidetes    115
4        2      Firmicutes   6433
5        2  Proteobacteria   1130
6        2  Actinobacteria    754
7        2   Bacteroidetes    555

In [41]:
bacteria_data['year'] = 2013
bacteria_data

patient          phylum  value  year
0        1      Firmicutes    632  2013
1        1  Proteobacteria   1638  2013
2        1  Actinobacteria    569  2013
3        1   Bacteroidetes    115  2013
4        2      Firmicutes   6433  2013
5        2  Proteobacteria   1130  2013
6        2  Actinobacteria    754  2013
7        2   Bacteroidetes    555  2013

In [42]:
bacteria_data.phylum

0        Firmicutes
1    Proteobacteria
2    Actinobacteria
3     Bacteroidetes
4        Firmicutes
5    Proteobacteria
6    Actinobacteria
7     Bacteroidetes
Name: phylum, dtype: object

In [43]:
treatment = pd.Series([0]*4 + [1] * 2)
treatment

0    0
1    0
2    0
3    0
4    1
5    1
dtype: int64

In [45]:
bacteria_data['treatment'] = treatment
bacteria_data

patient          phylum  value  year  treatment
0        1      Firmicutes    632  2013        0.0
1        1  Proteobacteria   1638  2013        0.0
2        1  Actinobacteria    569  2013        0.0
3        1   Bacteroidetes    115  2013        0.0
4        2      Firmicutes   6433  2013        1.0
5        2  Proteobacteria   1130  2013        1.0
6        2  Actinobacteria    754  2013        NaN
7        2   Bacteroidetes    555  2013        NaN

In [46]:
bacteria_data.values

array([[1, 'Firmicutes', 632, 2013, 0.0],
       [1, 'Proteobacteria', 1638, 2013, 0.0],
       [1, 'Actinobacteria', 569, 2013, 0.0],
       [1, 'Bacteroidetes', 115, 2013, 0.0],
       [2, 'Firmicutes', 6433, 2013, 1.0],
       [2, 'Proteobacteria', 1130, 2013, 1.0],
       [2, 'Actinobacteria', 754, 2013, nan],
       [2, 'Bacteroidetes', 555, 2013, nan]], dtype=object)

In [47]:
df = pd.DataFrame({'foo': [1,2,3], 'bar': [0.4, -1.0, 4.5]})
df.values, df.values.dtype

(array([[ 1. ,  0.4],
        [ 2. , -1. ],
        [ 3. ,  4.5]]),
 dtype('float64'))

In [48]:
bacteria_data.index[0] = 15

TypeError: Index does not support mutable operations

In [49]:
bacteria2.index = bacteria.index
bacteria2

phylum
Firmicutes           NaN
Proteobacteria     632.0
Actinobacteria    1632.0
Bacteroidetes      569.0
dtype: float64

In [50]:
medals = pd.read_table('olympics.2018.txt', sep='\t', index_col=0, header=None, names=['country', 'medals', 'population'])
medals.head()

medals  population
country                      
Tonga           1       96165
Bahamas         1      281584
Jamaica         6     2589043
Cuba           25    10952046
Australia      41    18348078

In [51]:
oecd_site = 'https://www.oecd.org/about/budget/member-countries-budget-contributions.htm'

In [52]:
pd.read_html(oecd_site)

[                                                    0               1
 0   Member Countries' percentage shares of Part I ...             NaN
 1                                    Member Countries  % Contribution
 2                                           AUSTRALIA             3.1
 3                                             AUSTRIA             1.5
 4                                             BELGIUM             1.7
 5                                              CANADA             3.5
 6                                               CHILE             1.2
 7                                      CZECH REPUBLIC             1.1
 8                                             DENMARK             1.4
 9                                             ESTONIA             0.9
 10                                            FINLAND             1.3
 11                                             FRANCE             5.2
 12                                            GERMANY             7.2
 13   

In [53]:
mb = pd.read_csv('microbiome.csv')

In [54]:
pd.read_csv('microbiome.csv', skiprows=[3,4,6]).head()

Taxon  Patient  Tissue  Stool
0  Firmicutes        1     632    305
1  Firmicutes        2     136   4182
2  Firmicutes        5     831   8605
3  Firmicutes        7     718    717
4  Firmicutes        8     173     33

In [56]:
few_recs = pd.read_csv('microbiome.csv', nrows=4)
few_recs

Taxon  Patient  Tissue  Stool
0  Firmicutes        1     632    305
1  Firmicutes        2     136   4182
2  Firmicutes        3    1174    703
3  Firmicutes        4     408   3946

In [57]:
data_chunks = pd.read_csv('microbiome.csv', chunksize=5)
data_chunks

In [58]:
next(data_chunks)

Taxon  Patient  Tissue  Stool
0  Firmicutes        1     632    305
1  Firmicutes        2     136   4182
2  Firmicutes        3    1174    703
3  Firmicutes        4     408   3946
4  Firmicutes        5     831   8605

In [59]:
mb = pd.read_csv('microbiome.csv', index_col=['Taxon', 'Patient'])
mb.head()

Tissue  Stool
Taxon      Patient               
Firmicutes 1           632    305
           2           136   4182
           3          1174    703
           4           408   3946
           5           831   8605

In [60]:
mb.index

MultiIndex([('Firmicutes',  1),
            ('Firmicutes',  2),
            ('Firmicutes',  3),
            ('Firmicutes',  4),
            ('Firmicutes',  5),
            ('Firmicutes',  6),
            ('Firmicutes',  7),
            ('Firmicutes',  8),
            ('Firmicutes',  9),
            ('Firmicutes', 10)],
           names=['Taxon', 'Patient'])

In [61]:
mb.loc[('Firmicutes', 2)]

Tissue     136
Stool     4182
Name: (Firmicutes, 2), dtype: int64

In [62]:
mb.xs(1, level='Patient')

Tissue  Stool
Taxon                    
Firmicutes     632    305

In [63]:
mb.swaplevel('Patient', 'Taxon').head()

Tissue  Stool
Patient Taxon                    
1       Firmicutes     632    305
2       Firmicutes     136   4182
3       Firmicutes    1174    703
4       Firmicutes     408   3946
5       Firmicutes     831   8605

## Jonathan Doolittle